#!/bin/sh
set -eu

if [ -x /usr/bin/google-chrome-stable ]; then
  exec /usr/bin/google-chrome-stable --no-sandbox --disable-dev-shm-usage "$@"
fi

exec /usr/bin/chromium --no-sandbox --disable-dev-shm-usage "$@"
